- pipeline.id: main
  pipeline.workers: 1
  queue.type: persisted
  queue.drain: true
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

- pipeline.id: talog
  pipeline.workers: 1
  queue.type: persisted
  queue.drain: true
  path.config: "/usr/share/logstash/pipeline/lemo.conf"
